travis:
  secure:
    BINSTAR_TOKEN: Tu9w+5k25vReuI33KQGuxvg36xDpjKqKpKlgLTeHIrbD4q2c3r6t/8WWFGlT3vA9UjdIjM1T49Kgmxs00m3EaO5hPV8g67OcFb2acFmznEc1X4w9xceA2SdmjqTi+DTi9l2JVoISwuh7DwBaoVE+2uqBOdFQEkevqTm5uR4m77taPirSRVXkEA8CucfHUHEg4meQC+0sRC6yt40/mnhNwYdMQyFqQZqrmQudg6Y+TXAlAq+k+0qaQuKCFECdINV5/xfDB2Sn4ueaf5w+md1bO/Su+CcZvH2YRmmwFlPX3Lz5Qx/CyhAyW1ZAn1sEMSFPQcjeEUNyBYAlJGXTxGHrg8GqbESxUA7RbDSKl1h/xOesY6HS0bX++r4NEoDBqv7ZCvgGetFb4t4kdUrdAwbRO9kV9X3hkMORDkMwhwopfM5e+ruVY4ygyF42XpVDXK+h1neYvmMy5kkw1nOJgBFD0QYPmXKdfIrPPIHcHWLHHHzl2vnuzad5iAUjtDUxV283gM7NGGCGsQSxzkzYjaRrzr2ozazHgQleCd3pQvxYZt4Ym4aNI0WQRvKsyEpDKKW8kE79+kemVOqHDQ8mYyQfisK0F9G8C/uZEuXABZ0eKAcIgkgt5TkoJ+YS0K2eqV8X2TJY3Wa7N6sHrEmnIiDxiPG+ig+aPFFbvA2SKZSkpBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
